sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source utils.sh
- alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
- echo $alpine_arm_sha
- moodle_arm_sha=$(get_manifest_sha "neethumohan1212/moodle:latest" "arm")
- echo $moodle_arm_sha
- flag_arm=$(is_base "treehouses/alpine@"$alpine_arm_sha "neethumohan1212/moodle@"$moodle_arm_sha)
- echo $flag_arm
- alpine_amd64_sha=$(get_manifest_sha "treehouses/alpine:latest" "amd64")
- echo $alpine_amd64_sha
- moodle_amd64_sha=$(get_manifest_sha "neethumohan1212/moodle:latest" "amd64")
- echo $moodle_amd64_sha
- flag_amd64=$(is_base "treehouses/alpine@"$alpine_amd64_sha "neethumohan1212/moodle@"$moodle_amd64_sha)
- echo $flag_amd64
- alpine_arm64_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm64")
- echo $alpine_arm64_sha
- moodle_arm64_sha=$(get_manifest_sha "neethumohan1212/moodle:latest" "arm64")
- echo $moodle_arm64_sha
- flag_arm64=$(is_base "treehouses/alpine@"$alpine_arm64_sha "neethumohan1212/moodle@"$moodle_arm64_sha)
- echo $flag_arm64
- echo $DOCKERAPIKEY | docker login -u "neethumohan1212" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- build_image "treehouses/alpine:latest" arm "neethumohan1212/moodle" $flag_arm
- build_image "treehouses/alpine:latest" arm64 "neethumohan1212/moodle" $flag_arm64
- build_image "treehouses/alpine:latest" amd64 "neethumohan1212/moodle" $flag_amd64
- flag=$(change $flag_arm $flag_arm64 $flag_amd64)
- flag="true"
- echo $flag
before_deploy:
- deploy_image "neethumohan1212/moodle" arm
- deploy_image "neethumohan1212/moodle" arm64
- deploy_image "neethumohan1212/moodle" amd64
- tag1="latest"
- tag2=$(date +%Y%m%d%H%M)
- echo $tag2
- create_manifests neethumohan1212/moodle $tag1 $tag2 neethumohan1212/moodle-tags:amd64
  neethumohan1212/moodle-tags:arm neethumohan1212/moodle-tags:arm64
- docker manifest inspect neethumohan1212/moodle:$tag1
- docker manifest inspect neethumohan1212/moodle:$tag2
deploy:
- provider: script
  script: docker manifest push neethumohan1212/moodle:$tag1; docker manifest push
    neethumohan1212/moodle:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
  - secure: LOA8B0AW3ZUbcKsN6xtxDiMAjHa7Q9YZAu26Ib1ixyvHpCftQWkFRAT4W3GOvrIWekSfr3JgLI32DURL2rllwV+00Cz/JuSKb8/i3ZohmWHSKrfzDlVHWELeW0n1WU1myZ3IZTr3yqz/k+W23+P1UqHb3MbFVn5BEllkNkOnB+i+6iVMF+4U/jJ7kTHgf3LWeqo47F4zcPNDdZdpTkkpfbuDJbXq96DX/Rnts08NNpjcVY9hleAdJtUrZz1QjHLk1tDwyBTaRBqpRzm7f9GnT7aSEJqA6eHcGVIpFEpmEK/YRA+kLcYzs7kkADhof9ggEKmK5R4klLgM1NFQlvthXro444XXbYgo/FwdPkNmre0jezulhuAW8/97XdI+fXD2obbuWZAx6IdQUuVjFRDaTO/yU2ILES4McESam1yUqGJuVOULASu8beU+/yUVdoGtdNF+fSYhxwtlbpHzusVODnqf6GmcuMGzi1MPW8dVqHe2lQaNdxi+ttxJChBhY3JO2KFj96R5H8ofNz4orkHNZfARlXOctA4dkjWdfzyR4BxVokMiV/H6CuXua2VF9VtcCAbDa7ztoHAEnH8C1TXg6jq8OsFooHn6+RLWC0rlMKq70typdHlxWvzK+Q5o78YaFfKkQi/dK9JJI4N19YGnlm9t4NmeMgI20rjWfvyZVFs=
