sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source utils.sh
- alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
- echo $alpine_arm_sha
- moodle_arm_sha=$(get_manifest_sha "treehouses/moodle:latest" "arm")
- echo $moodle_arm_sha
- flag_arm=$(is_base "treehouses/alpine@"$alpine_arm_sha "treehouses/moodle@"$moodle_arm_sha)
- echo $flag_arm
- alpine_amd64_sha=$(get_manifest_sha "treehouses/alpine:latest" "amd64")
- echo $alpine_amd64_sha
- moodle_amd64_sha=$(get_manifest_sha "treehouses/moodle:latest" "amd64")
- echo $moodle_amd64_sha
- flag_amd64=$(is_base "treehouses/alpine@"$alpine_amd64_sha "treehouses/moodle@"$moodle_amd64_sha)
- echo $flag_amd64
- alpine_arm64_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm64")
- echo $alpine_arm64_sha
- moodle_arm64_sha=$(get_manifest_sha "treehouses/moodle:latest" "arm64")
- echo $moodle_arm64_sha
- flag_arm64=$(is_base "treehouses/alpine@"$alpine_arm64_sha "treehouses/moodle@"$moodle_arm64_sha)
- echo $flag_arm64
- echo $DOCKERAPIKEY | docker login -u "neethumohan1212" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- build_image "treehouses/alpine:latest" arm "treehouses/moodle" $flag_arm
- build_image "treehouses/alpine:latest" arm64 "treehouses/moodle" $flag_arm64
- build_image "treehouses/alpine:latest" amd64 "treehouses/moodle" $flag_amd64
- flag=$(change $flag_arm $flag_arm64 $flag_amd64)
- flag="true"
- echo $flag
before_deploy:
- deploy_image "treehouses/moodle" arm
- deploy_image "treehouses/moodle" arm64
- deploy_image "treehouses/moodle" amd64
- tag1="latest"
- tag2=$(date +%Y%m%d%H%M)
- echo $tag2
- create_manifests treehouses/moodle $tag1 $tag2 treehouses/moodle-tags:amd64 treehouses/moodle-tags:arm
  treehouses/moodle-tags:arm64
- docker manifest inspect treehouses/moodle:$tag1
- docker manifest inspect treehouses/moodle:$tag2
deploy:
- provider: script
  script: docker manifest push treehouses/moodle:$tag1; docker manifest push treehouses/moodle:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
  - secure: gSDM0Sgzk83VPSj2zcol+NlALHf0KcJtnciWegNsciCvDJ6ZFWhNh4TFfWadHPCGrGyyud4Gt3n6MOvGuicWDjiIq0u1k4UoVFCwsVUBJ5OMSIDGOzc0idgbRvam8kDifaaUy3v2srdDprZ3NrCB1Y4Azk/wJSQtkBgUGYoTVliKDtIONOnuSGt0YkD6UUES2q52ryUwX7fmln0tOBNgsBLRAqf0hy3Nvk8kldUvuC4uXEGuenIny73JybPd5H9q+c8tNjAGkVS4XJsqA+nvXl4rqD7g8YYv2qlVZgMSoZdWLo6IxJU9a3qXXTOuhBUi2PcmCSIkA7uOEnf/I3zrauClxOdkcKiO9EBcuRiESnnK5/n/lbItYJoekLd0SmBpM0suCHAvvujRR9BkF9WqslM+NXwtGXVRqUrR2PD/jS5rj6hsIkjZ/++290VJM1kCPfddvxDQl8HYCDMAO6BGqJINadDecFd0Pv/JMLUpZi3ydEeOzSgVyI9RVQv29/VvnxjfZ86D78f71kHKs21nzBsGBXJFKYsG8vjHG/L9/Sv2DWsEZ6PNX9Q2yrqZPy+y68JtwMlFolCaL4HMqCmDFnPsbB8BBmypGwKwxEc17wUGS1NP7SbRY3lrtWQ0DggtuXwjoCQmSNpc3ZoiDG7o9CYFWOJkM9HVw7Y7UuBkWHA=
